//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WarSituation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WarSituation() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCP.Resources.Views.Home.WarSituation", typeof(WarSituation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 車輛稼動率 的當地語系化字串。
        /// </summary>
        public static string Activation {
            get {
                return ResourceManager.GetString("Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 車輛任務狀態 的當地語系化字串。
        /// </summary>
        public static string AgvTaskStatus {
            get {
                return ResourceManager.GetString("AgvTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 異常總數 的當地語系化字串。
        /// </summary>
        public static string AlarmCount {
            get {
                return ResourceManager.GetString("AlarmCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前電量 的當地語系化字串。
        /// </summary>
        public static string Betrry {
            get {
                return ResourceManager.GetString("Betrry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 車輛 的當地語系化字串。
        /// </summary>
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 名稱 的當地語系化字串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 前往位置 的當地語系化字串。
        /// </summary>
        public static string NextPosition {
            get {
                return ResourceManager.GetString("NextPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前位置 的當地語系化字串。
        /// </summary>
        public static string NowPosition {
            get {
                return ResourceManager.GetString("NowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態 的當地語系化字串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 今日任務總數 的當地語系化字串。
        /// </summary>
        public static string TaskCount {
            get {
                return ResourceManager.GetString("TaskCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 歷史任務統計 的當地語系化字串。
        /// </summary>
        public static string TaskList {
            get {
                return ResourceManager.GetString("TaskList", resourceCulture);
            }
        }
    }
}
