<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BaseOutputPath>..\Release</BaseOutputPath>
    <SatelliteResourceLanguages>en;zh-TW</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\signalr\**" />
    <Content Remove="wwwroot\signalr\**" />
    <EmbeddedResource Remove="wwwroot\signalr\**" />
    <None Remove="wwwroot\signalr\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Views\Group\Group.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.15">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.jQuery.Unobtrusive.Ajax" Version="3.2.6" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.17" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NLog" Version="6.0.7" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Views\Home\WarSituation.resx">
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>

</Project>
